# -*- coding: utf-8 -*-
"""Descmat aula 03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CMHe8zCZc2LQJrjO3Fi4Q72MlRQ_-GD
"""

# Funções e estruturas condicionais

def media_aritmetica(a, b, c):
    return (a + b + c) / 3

def celsius_para_fahrenheit(celsius):
    return celsius * 9/5 + 32

def avalia_desempenho(nota):
    if nota >= 90:
        return "Excelente"
    elif nota >= 70:
        return "Bom"
    elif nota >= 50:
        return "Regular"
    else:
        return "Insuficiente"

def calculadora(a, b, operacao):
    if operacao.lower() == "soma":
        resultado_soma = a + b
        return converter_m_cm(resultado_soma)
    elif operacao.lower() == "subtracao":
        resultado_subtracao = a - b
        return converter_m_cm(resultado_subtracao)
    elif operacao.lower() == "multiplicacao":
        resultado_multiplicacao = a * b
        return converter_m_cm(resultado_multiplicacao)
    elif operacao.lower() == "divisao":
        if b != 0:
            resultado_divisao = a / b
            return converter_m_cm(resultado_divisao)
        else:
            print("Não é possível dividir por zero")
    elif operacao.lower() == "potencia":
        resultado_potencia = a ** b
        return converter_m_cm(resultado_potencia)
    else:
        print("Operação inválida")

def converter_m_cm(metros):
    return metros * 100


# Funções recursivas

def fatorial_recursivo(n):
    if n == 0 or n == 1:
        return 1
    return n * fatorial_recursivo(n - 1)

def fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

def soma_recursiva(n):
    if n <= 1:
        return n
    return n + soma_recursiva(n - 1)

# Chamada das funções

print(media_aritmetica(10, 20, 30))
print(celsius_para_fahrenheit(30))
print(avalia_desempenho(80))
print(calculadora(10, 20, "soma"))
print(converter_m_cm(10))

print(fatorial_recursivo(5))
print(fibonacci(10))
print(soma_recursiva(5))

