# -*- coding: utf-8 -*-
"""Atividade de POO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GePPgUe3KTwcpp49vKstYBTXrC0O6ld

## Questão 1: Implementação de uma Classe para Representar Frações

Crie uma classe `Fracao` que represente uma fração matemática, contendo numerador e denominador. A classe deve implementar as seguintes funcionalidades:

1. **Adição, subtração, multiplicação e divisão de frações.**
2. **Comparação entre frações** (igualdade, maior que, menor que).
3. **Simplificação automática** da fração após cada operação.
4. **Conversão da fração para número decimal.**
5. **Impressão no formato** `numerador/denominador`.

### Exemplo de uso:

```python
f1 = Fracao(1, 2)
f2 = Fracao(3, 4)

soma = f1 + f2  # Deve retornar 5/4
produto = f1 * f2  # Deve retornar 3/8
"""

import math

class Fracao:
    def __init__(self, numerador, denominador):
        if denominador == 0:
            raise ValueError("O denominador não pode ser zero.")
        self.numerador = numerador
        self.denominador = denominador
        self.simplificar()

    def simplificar(self):
        # Encontra o maior divisor comum (MDC) para simplificar a fração
        mdc = math.gcd(self.numerador, self.denominador)
        self.numerador //= mdc
        self.denominador //= mdc
        # Garante que o denominador seja sempre positivo
        if self.denominador < 0:
            self.numerador *= -1
            self.denominador *= -1

    def __str__(self):
        return f"{self.numerador}/{self.denominador}"

    def __add__(self, other):
        # Soma de frações: (a/b) + (c/d) = (a*d + b*c) / (b*d)
        novo_numerador = self.numerador * other.denominador + self.denominador * other.numerador
        novo_denominador = self.denominador * other.denominador
        return Fracao(novo_numerador, novo_denominador)

    def __sub__(self, other):
        # Subtração de frações: (a/b) - (c/d) = (a*d - b*c) / (b*d)
        novo_numerador = self.numerador * other.denominador - self.denominador * other.numerador
        novo_denominador = self.denominador * other.denominador
        return Fracao(novo_numerador, novo_denominador)

    def __mul__(self, other):
        # Multiplicação de frações: (a/b) * (c/d) = (a*c) / (b*d)
        novo_numerador = self.numerador * other.numerador
        novo_denominador = self.denominador * other.denominador
        return Fracao(novo_numerador, novo_denominador)

    def __truediv__(self, other):
        # Divisão de frações: (a/b) / (c/d) = (a*d) / (b*c)
        novo_numerador = self.numerador * other.denominador
        novo_denominador = self.denominador * other.numerador
        return Fracao(novo_numerador, novo_denominador)

    def __eq__(self, other):
        # Verifica igualdade entre duas frações
        return self.numerador == other.numerador and self.denominador == other.denominador

    def __lt__(self, other):
        # Verifica se uma fração é menor que a outra: (a/b) < (c/d)
        return self.numerador * other.denominador < other.numerador * self.denominador

    def __le__(self, other):
        # Verifica se uma fração é menor ou igual a outra
        return self.numerador * other.denominador <= other.numerador * self.denominador

    def __gt__(self, other):
        # Verifica se uma fração é maior que a outra
        return self.numerador * other.denominador > other.numerador * self.denominador

    def __ge__(self, other):
        # Verifica se uma fração é maior ou igual a outra
        return self.numerador * other.denominador >= other.numerador * self.denominador

    def decimal(self):
        # Converte a fração para um número decimal
        return self.numerador / self.denominador

f1 = Fracao(1, 2)
f2 = Fracao(3, 4)

soma = f1 + f2
produto = f1 * f2

print(f"Soma: {soma}")  # Saída: 5/4
print(f"Produto: {produto}")  # Saída: 3/8
print(f"Decimal de f1: {f1.decimal()}")  # Saída: 0.5
